export default {
  PRIMARY_COLOR: '#2aabb8',
  SECONDARY_COLOR: '#2aabb8',

  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',

  BACKGROUND_COLOR_LIGHT: '#ebe9e9',
  ACTIVE_TAB_COLOR: 'green',
  INACTIVE_TAB_COLOR: 'grey',

  BUTTON_RADIUS: 5,
  CARD_RADIUS: 5,

  CONTAINER_PADDING: 16,
  TEXT_INPUT_PADDING: 10,
};
